/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LIVEKALMAN_RX_V1_RX_V1_RECEIVER_PB_H_INCLUDED
#define PB_LIVEKALMAN_RX_V1_RX_V1_RECEIVER_PB_H_INCLUDED
#include <pb.h>
#include "common/v1/common.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(64) livekalman_rx_v1_TxFrame_reference_bits_t;
typedef PB_BYTES_ARRAY_T(2048) livekalman_rx_v1_TxFrame_packed_samples_t;
typedef struct _livekalman_rx_v1_TxFrame {
    char run_id[48];
    uint64_t stream_id;
    uint64_t sequence;
    uint64_t first_sample_index;
    uint32_t sample_rate_hz;
    uint32_t samples_per_symbol;
    uint64_t capture_timestamp_us;
    uint64_t config_version;
    pb_size_t samples_count;
    float samples[512];
    livekalman_rx_v1_TxFrame_reference_bits_t reference_bits;
    livekalman_common_v1_SampleFormat sample_format;
    livekalman_rx_v1_TxFrame_packed_samples_t packed_samples;
    /* Optional application metadata. Payload bytes are carried by the modulated
 samples and reconstructed after the receiver makes BPSK decisions. */
    bool has_media;
    livekalman_common_v1_MediaDescriptor media;
    uint64_t media_offset;
    bool media_end;
    uint32_t payload_byte_count;
    /* True when the payload bytes were XORed with the per-frame keystream from
 shared/dsp.Scramble (keyed by sequence) before modulation, so the channel
 bits are balanced for the receiver's DC tracker. The receiver reverses it
 after demodulation. Reference bits always describe the transmitted bits. */
    bool scrambled;
} livekalman_rx_v1_TxFrame;

typedef struct _livekalman_rx_v1_RxFeedback {
    uint64_t sequence;
    float snr_db;
    float noise_variance;
    uint64_t compared_bits;
    uint64_t bit_errors;
    float ber;
    double latency_ms;
    uint64_t active_config_version;
    uint32_t queue_depth;
} livekalman_rx_v1_RxFeedback;

typedef struct _livekalman_rx_v1_RxConfig {
    uint64_t command_id;
    uint64_t version;
    uint64_t effective_sequence;
    float kalman_q;
    float kalman_r;
    bool reset_state;
} livekalman_rx_v1_RxConfig;

typedef struct _livekalman_rx_v1_ApplyRxReply {
    bool accepted;
    pb_callback_t reason;
    uint64_t applied_version;
} livekalman_rx_v1_ApplyRxReply;

typedef struct _livekalman_rx_v1_RxStatus {
    uint64_t active_version;
    bool stream_active;
    uint64_t last_sequence;
    uint64_t sequence_gaps;
} livekalman_rx_v1_RxStatus;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define livekalman_rx_v1_TxFrame_init_default    {"", 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, _livekalman_common_v1_SampleFormat_MIN, {0, {0}}, false, livekalman_common_v1_MediaDescriptor_init_default, 0, 0, 0, 0}
#define livekalman_rx_v1_RxFeedback_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define livekalman_rx_v1_RxConfig_init_default   {0, 0, 0, 0, 0, 0}
#define livekalman_rx_v1_ApplyRxReply_init_default {0, {{NULL}, NULL}, 0}
#define livekalman_rx_v1_RxStatus_init_default   {0, 0, 0, 0}
#define livekalman_rx_v1_TxFrame_init_zero       {"", 0, 0, 0, 0, 0, 0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, {0, {0}}, _livekalman_common_v1_SampleFormat_MIN, {0, {0}}, false, livekalman_common_v1_MediaDescriptor_init_zero, 0, 0, 0, 0}
#define livekalman_rx_v1_RxFeedback_init_zero    {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define livekalman_rx_v1_RxConfig_init_zero      {0, 0, 0, 0, 0, 0}
#define livekalman_rx_v1_ApplyRxReply_init_zero  {0, {{NULL}, NULL}, 0}
#define livekalman_rx_v1_RxStatus_init_zero      {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define livekalman_rx_v1_TxFrame_run_id_tag      1
#define livekalman_rx_v1_TxFrame_stream_id_tag   2
#define livekalman_rx_v1_TxFrame_sequence_tag    3
#define livekalman_rx_v1_TxFrame_first_sample_index_tag 4
#define livekalman_rx_v1_TxFrame_sample_rate_hz_tag 5
#define livekalman_rx_v1_TxFrame_samples_per_symbol_tag 6
#define livekalman_rx_v1_TxFrame_capture_timestamp_us_tag 7
#define livekalman_rx_v1_TxFrame_config_version_tag 8
#define livekalman_rx_v1_TxFrame_samples_tag     9
#define livekalman_rx_v1_TxFrame_reference_bits_tag 10
#define livekalman_rx_v1_TxFrame_sample_format_tag 11
#define livekalman_rx_v1_TxFrame_packed_samples_tag 12
#define livekalman_rx_v1_TxFrame_media_tag       13
#define livekalman_rx_v1_TxFrame_media_offset_tag 14
#define livekalman_rx_v1_TxFrame_media_end_tag   15
#define livekalman_rx_v1_TxFrame_payload_byte_count_tag 16
#define livekalman_rx_v1_TxFrame_scrambled_tag   17
#define livekalman_rx_v1_RxFeedback_sequence_tag 1
#define livekalman_rx_v1_RxFeedback_snr_db_tag   2
#define livekalman_rx_v1_RxFeedback_noise_variance_tag 3
#define livekalman_rx_v1_RxFeedback_compared_bits_tag 4
#define livekalman_rx_v1_RxFeedback_bit_errors_tag 5
#define livekalman_rx_v1_RxFeedback_ber_tag      6
#define livekalman_rx_v1_RxFeedback_latency_ms_tag 7
#define livekalman_rx_v1_RxFeedback_active_config_version_tag 8
#define livekalman_rx_v1_RxFeedback_queue_depth_tag 9
#define livekalman_rx_v1_RxConfig_command_id_tag 1
#define livekalman_rx_v1_RxConfig_version_tag    2
#define livekalman_rx_v1_RxConfig_effective_sequence_tag 3
#define livekalman_rx_v1_RxConfig_kalman_q_tag   4
#define livekalman_rx_v1_RxConfig_kalman_r_tag   5
#define livekalman_rx_v1_RxConfig_reset_state_tag 6
#define livekalman_rx_v1_ApplyRxReply_accepted_tag 1
#define livekalman_rx_v1_ApplyRxReply_reason_tag 2
#define livekalman_rx_v1_ApplyRxReply_applied_version_tag 3
#define livekalman_rx_v1_RxStatus_active_version_tag 1
#define livekalman_rx_v1_RxStatus_stream_active_tag 2
#define livekalman_rx_v1_RxStatus_last_sequence_tag 3
#define livekalman_rx_v1_RxStatus_sequence_gaps_tag 4

/* Struct field encoding specification for nanopb */
#define livekalman_rx_v1_TxFrame_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   run_id,            1) \
X(a, STATIC,   SINGULAR, UINT64,   stream_id,         2) \
X(a, STATIC,   SINGULAR, UINT64,   sequence,          3) \
X(a, STATIC,   SINGULAR, UINT64,   first_sample_index,   4) \
X(a, STATIC,   SINGULAR, UINT32,   sample_rate_hz,    5) \
X(a, STATIC,   SINGULAR, UINT32,   samples_per_symbol,   6) \
X(a, STATIC,   SINGULAR, UINT64,   capture_timestamp_us,   7) \
X(a, STATIC,   SINGULAR, UINT64,   config_version,    8) \
X(a, STATIC,   REPEATED, FLOAT,    samples,           9) \
X(a, STATIC,   SINGULAR, BYTES,    reference_bits,   10) \
X(a, STATIC,   SINGULAR, UENUM,    sample_format,    11) \
X(a, STATIC,   SINGULAR, BYTES,    packed_samples,   12) \
X(a, STATIC,   OPTIONAL, MESSAGE,  media,            13) \
X(a, STATIC,   SINGULAR, UINT64,   media_offset,     14) \
X(a, STATIC,   SINGULAR, BOOL,     media_end,        15) \
X(a, STATIC,   SINGULAR, UINT32,   payload_byte_count,  16) \
X(a, STATIC,   SINGULAR, BOOL,     scrambled,        17)
#define livekalman_rx_v1_TxFrame_CALLBACK NULL
#define livekalman_rx_v1_TxFrame_DEFAULT NULL
#define livekalman_rx_v1_TxFrame_media_MSGTYPE livekalman_common_v1_MediaDescriptor

#define livekalman_rx_v1_RxFeedback_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   sequence,          1) \
X(a, STATIC,   SINGULAR, FLOAT,    snr_db,            2) \
X(a, STATIC,   SINGULAR, FLOAT,    noise_variance,    3) \
X(a, STATIC,   SINGULAR, UINT64,   compared_bits,     4) \
X(a, STATIC,   SINGULAR, UINT64,   bit_errors,        5) \
X(a, STATIC,   SINGULAR, FLOAT,    ber,               6) \
X(a, STATIC,   SINGULAR, DOUBLE,   latency_ms,        7) \
X(a, STATIC,   SINGULAR, UINT64,   active_config_version,   8) \
X(a, STATIC,   SINGULAR, UINT32,   queue_depth,       9)
#define livekalman_rx_v1_RxFeedback_CALLBACK NULL
#define livekalman_rx_v1_RxFeedback_DEFAULT NULL

#define livekalman_rx_v1_RxConfig_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   command_id,        1) \
X(a, STATIC,   SINGULAR, UINT64,   version,           2) \
X(a, STATIC,   SINGULAR, UINT64,   effective_sequence,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    kalman_q,          4) \
X(a, STATIC,   SINGULAR, FLOAT,    kalman_r,          5) \
X(a, STATIC,   SINGULAR, BOOL,     reset_state,       6)
#define livekalman_rx_v1_RxConfig_CALLBACK NULL
#define livekalman_rx_v1_RxConfig_DEFAULT NULL

#define livekalman_rx_v1_ApplyRxReply_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     accepted,          1) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            2) \
X(a, STATIC,   SINGULAR, UINT64,   applied_version,   3)
#define livekalman_rx_v1_ApplyRxReply_CALLBACK pb_default_field_callback
#define livekalman_rx_v1_ApplyRxReply_DEFAULT NULL

#define livekalman_rx_v1_RxStatus_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   active_version,    1) \
X(a, STATIC,   SINGULAR, BOOL,     stream_active,     2) \
X(a, STATIC,   SINGULAR, UINT64,   last_sequence,     3) \
X(a, STATIC,   SINGULAR, UINT64,   sequence_gaps,     4)
#define livekalman_rx_v1_RxStatus_CALLBACK NULL
#define livekalman_rx_v1_RxStatus_DEFAULT NULL

extern const pb_msgdesc_t livekalman_rx_v1_TxFrame_msg;
extern const pb_msgdesc_t livekalman_rx_v1_RxFeedback_msg;
extern const pb_msgdesc_t livekalman_rx_v1_RxConfig_msg;
extern const pb_msgdesc_t livekalman_rx_v1_ApplyRxReply_msg;
extern const pb_msgdesc_t livekalman_rx_v1_RxStatus_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define livekalman_rx_v1_TxFrame_fields &livekalman_rx_v1_TxFrame_msg
#define livekalman_rx_v1_RxFeedback_fields &livekalman_rx_v1_RxFeedback_msg
#define livekalman_rx_v1_RxConfig_fields &livekalman_rx_v1_RxConfig_msg
#define livekalman_rx_v1_ApplyRxReply_fields &livekalman_rx_v1_ApplyRxReply_msg
#define livekalman_rx_v1_RxStatus_fields &livekalman_rx_v1_RxStatus_msg

/* Maximum encoded size of messages (where known) */
/* livekalman_rx_v1_ApplyRxReply_size depends on runtime parameters */
#define LIVEKALMAN_RX_V1_RX_V1_RECEIVER_PB_H_MAX_SIZE livekalman_rx_v1_TxFrame_size
#define livekalman_rx_v1_RxConfig_size           45
#define livekalman_rx_v1_RxFeedback_size         74
#define livekalman_rx_v1_RxStatus_size           35
#define livekalman_rx_v1_TxFrame_size            5005

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
