/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "rx/v1/receiver.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(livekalman_rx_v1_TxFrame, livekalman_rx_v1_TxFrame, 2)


PB_BIND(livekalman_rx_v1_RxFeedback, livekalman_rx_v1_RxFeedback, AUTO)


PB_BIND(livekalman_rx_v1_RxConfig, livekalman_rx_v1_RxConfig, AUTO)


PB_BIND(livekalman_rx_v1_ApplyRxReply, livekalman_rx_v1_ApplyRxReply, AUTO)


PB_BIND(livekalman_rx_v1_RxStatus, livekalman_rx_v1_RxStatus, AUTO)



#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

