/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "common/v1/common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(livekalman_common_v1_Empty, livekalman_common_v1_Empty, AUTO)


PB_BIND(livekalman_common_v1_Capability, livekalman_common_v1_Capability, AUTO)


PB_BIND(livekalman_common_v1_Capability_AttributesEntry, livekalman_common_v1_Capability_AttributesEntry, AUTO)


PB_BIND(livekalman_common_v1_NodeInfo, livekalman_common_v1_NodeInfo, AUTO)


PB_BIND(livekalman_common_v1_NodeStatus, livekalman_common_v1_NodeStatus, AUTO)


PB_BIND(livekalman_common_v1_WatchNodeRequest, livekalman_common_v1_WatchNodeRequest, AUTO)


PB_BIND(livekalman_common_v1_MediaDescriptor, livekalman_common_v1_MediaDescriptor, AUTO)


PB_BIND(livekalman_common_v1_MediaEvent, livekalman_common_v1_MediaEvent, 2)


PB_BIND(livekalman_common_v1_WatchMediaRequest, livekalman_common_v1_WatchMediaRequest, AUTO)















