/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_LIVEKALMAN_COMMON_V1_COMMON_V1_COMMON_PB_H_INCLUDED
#define PB_LIVEKALMAN_COMMON_V1_COMMON_V1_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* SampleFormat makes the byte representation explicit for embedded producers. */
typedef enum _livekalman_common_v1_SampleFormat {
    livekalman_common_v1_SampleFormat_SAMPLE_FORMAT_UNSPECIFIED = 0,
    livekalman_common_v1_SampleFormat_SAMPLE_FORMAT_FLOAT32_LE = 1,
    livekalman_common_v1_SampleFormat_SAMPLE_FORMAT_INT16_LE = 2
} livekalman_common_v1_SampleFormat;

/* NodeRole identifies the independently deployable process behind an endpoint. */
typedef enum _livekalman_common_v1_NodeRole {
    livekalman_common_v1_NodeRole_NODE_ROLE_UNSPECIFIED = 0,
    livekalman_common_v1_NodeRole_NODE_ROLE_TRANSMITTER = 1,
    livekalman_common_v1_NodeRole_NODE_ROLE_RECEIVER = 2,
    livekalman_common_v1_NodeRole_NODE_ROLE_CONTROLLER = 3
} livekalman_common_v1_NodeRole;

typedef enum _livekalman_common_v1_HealthState {
    livekalman_common_v1_HealthState_HEALTH_STATE_UNSPECIFIED = 0,
    livekalman_common_v1_HealthState_HEALTH_STATE_STARTING = 1,
    livekalman_common_v1_HealthState_HEALTH_STATE_READY = 2,
    livekalman_common_v1_HealthState_HEALTH_STATE_DEGRADED = 3,
    livekalman_common_v1_HealthState_HEALTH_STATE_STOPPING = 4
} livekalman_common_v1_HealthState;

/* MediaType is the receiver's content classification. A producer may provide a
 hint, but the receiver derives the final value from the reconstructed bytes. */
typedef enum _livekalman_common_v1_MediaType {
    livekalman_common_v1_MediaType_MEDIA_TYPE_UNSPECIFIED = 0,
    livekalman_common_v1_MediaType_MEDIA_TYPE_BINARY = 1,
    livekalman_common_v1_MediaType_MEDIA_TYPE_TEXT = 2,
    livekalman_common_v1_MediaType_MEDIA_TYPE_IMAGE = 3,
    livekalman_common_v1_MediaType_MEDIA_TYPE_AUDIO = 4
} livekalman_common_v1_MediaType;

/* Modulation identifies how payload bits were converted into signal symbols. */
typedef enum _livekalman_common_v1_Modulation {
    livekalman_common_v1_Modulation_MODULATION_UNSPECIFIED = 0,
    livekalman_common_v1_Modulation_MODULATION_BPSK = 1
} livekalman_common_v1_Modulation;

/* PayloadEncoding is applied to bytes before modulation and reversed only
 after demodulation. BYTE_SHIFT is useful for teaching, not for security. */
typedef enum _livekalman_common_v1_PayloadEncoding {
    livekalman_common_v1_PayloadEncoding_PAYLOAD_ENCODING_UNSPECIFIED = 0,
    livekalman_common_v1_PayloadEncoding_PAYLOAD_ENCODING_RAW = 1,
    livekalman_common_v1_PayloadEncoding_PAYLOAD_ENCODING_BYTE_SHIFT = 2
} livekalman_common_v1_PayloadEncoding;

/* Struct definitions */
typedef struct _livekalman_common_v1_Empty {
    char dummy_field;
} livekalman_common_v1_Empty;

typedef struct _livekalman_common_v1_Capability {
    pb_callback_t name;
    pb_callback_t version;
    pb_callback_t attributes;
} livekalman_common_v1_Capability;

typedef struct _livekalman_common_v1_Capability_AttributesEntry {
    pb_callback_t key;
    pb_callback_t value;
} livekalman_common_v1_Capability_AttributesEntry;

typedef struct _livekalman_common_v1_NodeInfo {
    pb_callback_t node_id;
    pb_callback_t display_name;
    livekalman_common_v1_NodeRole role;
    pb_callback_t api_version;
    pb_callback_t listen_address;
    pb_callback_t capabilities;
} livekalman_common_v1_NodeInfo;

typedef struct _livekalman_common_v1_NodeStatus {
    pb_callback_t node_id;
    livekalman_common_v1_NodeRole role;
    livekalman_common_v1_HealthState health;
    bool active;
    bool peer_connected;
    pb_callback_t active_run_id;
    uint64_t active_config_version;
    uint64_t last_sequence;
    uint64_t uptime_ms;
    pb_callback_t message;
    uint64_t observed_at_unix_ms;
} livekalman_common_v1_NodeStatus;

typedef struct _livekalman_common_v1_WatchNodeRequest {
    uint32_t interval_ms;
} livekalman_common_v1_WatchNodeRequest;

typedef struct _livekalman_common_v1_MediaDescriptor {
    char transfer_id[40];
    char file_name[64];
    livekalman_common_v1_MediaType media_type_hint;
    char content_type_hint[48];
    uint64_t total_size;
    uint32_t crc32;
    livekalman_common_v1_Modulation modulation;
    livekalman_common_v1_PayloadEncoding encoding;
    uint32_t shift_key;
} livekalman_common_v1_MediaDescriptor;

/* MediaEvent is the one role-neutral output stream for text, image, audio and
 unknown binary data. Data is decoded application bytes, never signal samples. */
typedef struct _livekalman_common_v1_MediaEvent {
    bool has_media;
    livekalman_common_v1_MediaDescriptor media;
    livekalman_common_v1_MediaType detected_type;
    pb_callback_t detected_content_type;
    uint64_t offset;
    pb_callback_t data;
    bool end_of_stream;
    uint64_t received_size;
    bool checksum_valid;
    pb_callback_t message;
    uint64_t observed_at_unix_ms;
} livekalman_common_v1_MediaEvent;

typedef struct _livekalman_common_v1_WatchMediaRequest {
    pb_callback_t types;
} livekalman_common_v1_WatchMediaRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _livekalman_common_v1_SampleFormat_MIN livekalman_common_v1_SampleFormat_SAMPLE_FORMAT_UNSPECIFIED
#define _livekalman_common_v1_SampleFormat_MAX livekalman_common_v1_SampleFormat_SAMPLE_FORMAT_INT16_LE
#define _livekalman_common_v1_SampleFormat_ARRAYSIZE ((livekalman_common_v1_SampleFormat)(livekalman_common_v1_SampleFormat_SAMPLE_FORMAT_INT16_LE+1))

#define _livekalman_common_v1_NodeRole_MIN livekalman_common_v1_NodeRole_NODE_ROLE_UNSPECIFIED
#define _livekalman_common_v1_NodeRole_MAX livekalman_common_v1_NodeRole_NODE_ROLE_CONTROLLER
#define _livekalman_common_v1_NodeRole_ARRAYSIZE ((livekalman_common_v1_NodeRole)(livekalman_common_v1_NodeRole_NODE_ROLE_CONTROLLER+1))

#define _livekalman_common_v1_HealthState_MIN livekalman_common_v1_HealthState_HEALTH_STATE_UNSPECIFIED
#define _livekalman_common_v1_HealthState_MAX livekalman_common_v1_HealthState_HEALTH_STATE_STOPPING
#define _livekalman_common_v1_HealthState_ARRAYSIZE ((livekalman_common_v1_HealthState)(livekalman_common_v1_HealthState_HEALTH_STATE_STOPPING+1))

#define _livekalman_common_v1_MediaType_MIN livekalman_common_v1_MediaType_MEDIA_TYPE_UNSPECIFIED
#define _livekalman_common_v1_MediaType_MAX livekalman_common_v1_MediaType_MEDIA_TYPE_AUDIO
#define _livekalman_common_v1_MediaType_ARRAYSIZE ((livekalman_common_v1_MediaType)(livekalman_common_v1_MediaType_MEDIA_TYPE_AUDIO+1))

#define _livekalman_common_v1_Modulation_MIN livekalman_common_v1_Modulation_MODULATION_UNSPECIFIED
#define _livekalman_common_v1_Modulation_MAX livekalman_common_v1_Modulation_MODULATION_BPSK
#define _livekalman_common_v1_Modulation_ARRAYSIZE ((livekalman_common_v1_Modulation)(livekalman_common_v1_Modulation_MODULATION_BPSK+1))

#define _livekalman_common_v1_PayloadEncoding_MIN livekalman_common_v1_PayloadEncoding_PAYLOAD_ENCODING_UNSPECIFIED
#define _livekalman_common_v1_PayloadEncoding_MAX livekalman_common_v1_PayloadEncoding_PAYLOAD_ENCODING_BYTE_SHIFT
#define _livekalman_common_v1_PayloadEncoding_ARRAYSIZE ((livekalman_common_v1_PayloadEncoding)(livekalman_common_v1_PayloadEncoding_PAYLOAD_ENCODING_BYTE_SHIFT+1))




#define livekalman_common_v1_NodeInfo_role_ENUMTYPE livekalman_common_v1_NodeRole

#define livekalman_common_v1_NodeStatus_role_ENUMTYPE livekalman_common_v1_NodeRole
#define livekalman_common_v1_NodeStatus_health_ENUMTYPE livekalman_common_v1_HealthState


#define livekalman_common_v1_MediaDescriptor_media_type_hint_ENUMTYPE livekalman_common_v1_MediaType
#define livekalman_common_v1_MediaDescriptor_modulation_ENUMTYPE livekalman_common_v1_Modulation
#define livekalman_common_v1_MediaDescriptor_encoding_ENUMTYPE livekalman_common_v1_PayloadEncoding

#define livekalman_common_v1_MediaEvent_detected_type_ENUMTYPE livekalman_common_v1_MediaType

#define livekalman_common_v1_WatchMediaRequest_types_ENUMTYPE livekalman_common_v1_MediaType


/* Initializer values for message structs */
#define livekalman_common_v1_Empty_init_default  {0}
#define livekalman_common_v1_Capability_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define livekalman_common_v1_Capability_AttributesEntry_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define livekalman_common_v1_NodeInfo_init_default {{{NULL}, NULL}, {{NULL}, NULL}, _livekalman_common_v1_NodeRole_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define livekalman_common_v1_NodeStatus_init_default {{{NULL}, NULL}, _livekalman_common_v1_NodeRole_MIN, _livekalman_common_v1_HealthState_MIN, 0, 0, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define livekalman_common_v1_WatchNodeRequest_init_default {0}
#define livekalman_common_v1_MediaDescriptor_init_default {"", "", _livekalman_common_v1_MediaType_MIN, "", 0, 0, _livekalman_common_v1_Modulation_MIN, _livekalman_common_v1_PayloadEncoding_MIN, 0}
#define livekalman_common_v1_MediaEvent_init_default {false, livekalman_common_v1_MediaDescriptor_init_default, _livekalman_common_v1_MediaType_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define livekalman_common_v1_WatchMediaRequest_init_default {{{NULL}, NULL}}
#define livekalman_common_v1_Empty_init_zero     {0}
#define livekalman_common_v1_Capability_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define livekalman_common_v1_Capability_AttributesEntry_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define livekalman_common_v1_NodeInfo_init_zero  {{{NULL}, NULL}, {{NULL}, NULL}, _livekalman_common_v1_NodeRole_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define livekalman_common_v1_NodeStatus_init_zero {{{NULL}, NULL}, _livekalman_common_v1_NodeRole_MIN, _livekalman_common_v1_HealthState_MIN, 0, 0, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define livekalman_common_v1_WatchNodeRequest_init_zero {0}
#define livekalman_common_v1_MediaDescriptor_init_zero {"", "", _livekalman_common_v1_MediaType_MIN, "", 0, 0, _livekalman_common_v1_Modulation_MIN, _livekalman_common_v1_PayloadEncoding_MIN, 0}
#define livekalman_common_v1_MediaEvent_init_zero {false, livekalman_common_v1_MediaDescriptor_init_zero, _livekalman_common_v1_MediaType_MIN, {{NULL}, NULL}, 0, {{NULL}, NULL}, 0, 0, 0, {{NULL}, NULL}, 0}
#define livekalman_common_v1_WatchMediaRequest_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define livekalman_common_v1_Capability_name_tag 1
#define livekalman_common_v1_Capability_version_tag 2
#define livekalman_common_v1_Capability_attributes_tag 3
#define livekalman_common_v1_Capability_AttributesEntry_key_tag 1
#define livekalman_common_v1_Capability_AttributesEntry_value_tag 2
#define livekalman_common_v1_NodeInfo_node_id_tag 1
#define livekalman_common_v1_NodeInfo_display_name_tag 2
#define livekalman_common_v1_NodeInfo_role_tag   3
#define livekalman_common_v1_NodeInfo_api_version_tag 4
#define livekalman_common_v1_NodeInfo_listen_address_tag 5
#define livekalman_common_v1_NodeInfo_capabilities_tag 6
#define livekalman_common_v1_NodeStatus_node_id_tag 1
#define livekalman_common_v1_NodeStatus_role_tag 2
#define livekalman_common_v1_NodeStatus_health_tag 3
#define livekalman_common_v1_NodeStatus_active_tag 4
#define livekalman_common_v1_NodeStatus_peer_connected_tag 5
#define livekalman_common_v1_NodeStatus_active_run_id_tag 6
#define livekalman_common_v1_NodeStatus_active_config_version_tag 7
#define livekalman_common_v1_NodeStatus_last_sequence_tag 8
#define livekalman_common_v1_NodeStatus_uptime_ms_tag 9
#define livekalman_common_v1_NodeStatus_message_tag 10
#define livekalman_common_v1_NodeStatus_observed_at_unix_ms_tag 11
#define livekalman_common_v1_WatchNodeRequest_interval_ms_tag 1
#define livekalman_common_v1_MediaDescriptor_transfer_id_tag 1
#define livekalman_common_v1_MediaDescriptor_file_name_tag 2
#define livekalman_common_v1_MediaDescriptor_media_type_hint_tag 3
#define livekalman_common_v1_MediaDescriptor_content_type_hint_tag 4
#define livekalman_common_v1_MediaDescriptor_total_size_tag 5
#define livekalman_common_v1_MediaDescriptor_crc32_tag 6
#define livekalman_common_v1_MediaDescriptor_modulation_tag 7
#define livekalman_common_v1_MediaDescriptor_encoding_tag 8
#define livekalman_common_v1_MediaDescriptor_shift_key_tag 9
#define livekalman_common_v1_MediaEvent_media_tag 1
#define livekalman_common_v1_MediaEvent_detected_type_tag 2
#define livekalman_common_v1_MediaEvent_detected_content_type_tag 3
#define livekalman_common_v1_MediaEvent_offset_tag 4
#define livekalman_common_v1_MediaEvent_data_tag 5
#define livekalman_common_v1_MediaEvent_end_of_stream_tag 6
#define livekalman_common_v1_MediaEvent_received_size_tag 7
#define livekalman_common_v1_MediaEvent_checksum_valid_tag 8
#define livekalman_common_v1_MediaEvent_message_tag 9
#define livekalman_common_v1_MediaEvent_observed_at_unix_ms_tag 10
#define livekalman_common_v1_WatchMediaRequest_types_tag 1

/* Struct field encoding specification for nanopb */
#define livekalman_common_v1_Empty_FIELDLIST(X, a) \

#define livekalman_common_v1_Empty_CALLBACK NULL
#define livekalman_common_v1_Empty_DEFAULT NULL

#define livekalman_common_v1_Capability_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   version,           2) \
X(a, CALLBACK, REPEATED, MESSAGE,  attributes,        3)
#define livekalman_common_v1_Capability_CALLBACK pb_default_field_callback
#define livekalman_common_v1_Capability_DEFAULT NULL
#define livekalman_common_v1_Capability_attributes_MSGTYPE livekalman_common_v1_Capability_AttributesEntry

#define livekalman_common_v1_Capability_AttributesEntry_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   key,               1) \
X(a, CALLBACK, SINGULAR, STRING,   value,             2)
#define livekalman_common_v1_Capability_AttributesEntry_CALLBACK pb_default_field_callback
#define livekalman_common_v1_Capability_AttributesEntry_DEFAULT NULL

#define livekalman_common_v1_NodeInfo_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   node_id,           1) \
X(a, CALLBACK, SINGULAR, STRING,   display_name,      2) \
X(a, STATIC,   SINGULAR, UENUM,    role,              3) \
X(a, CALLBACK, SINGULAR, STRING,   api_version,       4) \
X(a, CALLBACK, SINGULAR, STRING,   listen_address,    5) \
X(a, CALLBACK, REPEATED, MESSAGE,  capabilities,      6)
#define livekalman_common_v1_NodeInfo_CALLBACK pb_default_field_callback
#define livekalman_common_v1_NodeInfo_DEFAULT NULL
#define livekalman_common_v1_NodeInfo_capabilities_MSGTYPE livekalman_common_v1_Capability

#define livekalman_common_v1_NodeStatus_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   node_id,           1) \
X(a, STATIC,   SINGULAR, UENUM,    role,              2) \
X(a, STATIC,   SINGULAR, UENUM,    health,            3) \
X(a, STATIC,   SINGULAR, BOOL,     active,            4) \
X(a, STATIC,   SINGULAR, BOOL,     peer_connected,    5) \
X(a, CALLBACK, SINGULAR, STRING,   active_run_id,     6) \
X(a, STATIC,   SINGULAR, UINT64,   active_config_version,   7) \
X(a, STATIC,   SINGULAR, UINT64,   last_sequence,     8) \
X(a, STATIC,   SINGULAR, UINT64,   uptime_ms,         9) \
X(a, CALLBACK, SINGULAR, STRING,   message,          10) \
X(a, STATIC,   SINGULAR, UINT64,   observed_at_unix_ms,  11)
#define livekalman_common_v1_NodeStatus_CALLBACK pb_default_field_callback
#define livekalman_common_v1_NodeStatus_DEFAULT NULL

#define livekalman_common_v1_WatchNodeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   interval_ms,       1)
#define livekalman_common_v1_WatchNodeRequest_CALLBACK NULL
#define livekalman_common_v1_WatchNodeRequest_DEFAULT NULL

#define livekalman_common_v1_MediaDescriptor_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   transfer_id,       1) \
X(a, STATIC,   SINGULAR, STRING,   file_name,         2) \
X(a, STATIC,   SINGULAR, UENUM,    media_type_hint,   3) \
X(a, STATIC,   SINGULAR, STRING,   content_type_hint,   4) \
X(a, STATIC,   SINGULAR, UINT64,   total_size,        5) \
X(a, STATIC,   SINGULAR, UINT32,   crc32,             6) \
X(a, STATIC,   SINGULAR, UENUM,    modulation,        7) \
X(a, STATIC,   SINGULAR, UENUM,    encoding,          8) \
X(a, STATIC,   SINGULAR, UINT32,   shift_key,         9)
#define livekalman_common_v1_MediaDescriptor_CALLBACK NULL
#define livekalman_common_v1_MediaDescriptor_DEFAULT NULL

#define livekalman_common_v1_MediaEvent_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  media,             1) \
X(a, STATIC,   SINGULAR, UENUM,    detected_type,     2) \
X(a, CALLBACK, SINGULAR, STRING,   detected_content_type,   3) \
X(a, STATIC,   SINGULAR, UINT64,   offset,            4) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              5) \
X(a, STATIC,   SINGULAR, BOOL,     end_of_stream,     6) \
X(a, STATIC,   SINGULAR, UINT64,   received_size,     7) \
X(a, STATIC,   SINGULAR, BOOL,     checksum_valid,    8) \
X(a, CALLBACK, SINGULAR, STRING,   message,           9) \
X(a, STATIC,   SINGULAR, UINT64,   observed_at_unix_ms,  10)
#define livekalman_common_v1_MediaEvent_CALLBACK pb_default_field_callback
#define livekalman_common_v1_MediaEvent_DEFAULT NULL
#define livekalman_common_v1_MediaEvent_media_MSGTYPE livekalman_common_v1_MediaDescriptor

#define livekalman_common_v1_WatchMediaRequest_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UENUM,    types,             1)
#define livekalman_common_v1_WatchMediaRequest_CALLBACK pb_default_field_callback
#define livekalman_common_v1_WatchMediaRequest_DEFAULT NULL

extern const pb_msgdesc_t livekalman_common_v1_Empty_msg;
extern const pb_msgdesc_t livekalman_common_v1_Capability_msg;
extern const pb_msgdesc_t livekalman_common_v1_Capability_AttributesEntry_msg;
extern const pb_msgdesc_t livekalman_common_v1_NodeInfo_msg;
extern const pb_msgdesc_t livekalman_common_v1_NodeStatus_msg;
extern const pb_msgdesc_t livekalman_common_v1_WatchNodeRequest_msg;
extern const pb_msgdesc_t livekalman_common_v1_MediaDescriptor_msg;
extern const pb_msgdesc_t livekalman_common_v1_MediaEvent_msg;
extern const pb_msgdesc_t livekalman_common_v1_WatchMediaRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define livekalman_common_v1_Empty_fields &livekalman_common_v1_Empty_msg
#define livekalman_common_v1_Capability_fields &livekalman_common_v1_Capability_msg
#define livekalman_common_v1_Capability_AttributesEntry_fields &livekalman_common_v1_Capability_AttributesEntry_msg
#define livekalman_common_v1_NodeInfo_fields &livekalman_common_v1_NodeInfo_msg
#define livekalman_common_v1_NodeStatus_fields &livekalman_common_v1_NodeStatus_msg
#define livekalman_common_v1_WatchNodeRequest_fields &livekalman_common_v1_WatchNodeRequest_msg
#define livekalman_common_v1_MediaDescriptor_fields &livekalman_common_v1_MediaDescriptor_msg
#define livekalman_common_v1_MediaEvent_fields &livekalman_common_v1_MediaEvent_msg
#define livekalman_common_v1_WatchMediaRequest_fields &livekalman_common_v1_WatchMediaRequest_msg

/* Maximum encoded size of messages (where known) */
/* livekalman_common_v1_Capability_size depends on runtime parameters */
/* livekalman_common_v1_Capability_AttributesEntry_size depends on runtime parameters */
/* livekalman_common_v1_NodeInfo_size depends on runtime parameters */
/* livekalman_common_v1_NodeStatus_size depends on runtime parameters */
/* livekalman_common_v1_MediaEvent_size depends on runtime parameters */
/* livekalman_common_v1_WatchMediaRequest_size depends on runtime parameters */
#define LIVEKALMAN_COMMON_V1_COMMON_V1_COMMON_PB_H_MAX_SIZE livekalman_common_v1_MediaDescriptor_size
#define livekalman_common_v1_Empty_size          0
#define livekalman_common_v1_MediaDescriptor_size 184
#define livekalman_common_v1_WatchNodeRequest_size 6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
